[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAND CR AT MOUTH COMMERCE CITY CO (3233) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "3233.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "3233-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 21,595"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21595

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 26,463"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26463

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 32,639"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32639

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 93,282"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93282

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 53,440"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53440

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 39,346"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39346

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 78,022"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78022

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 35,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35717

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 58,861"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58861

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 65,928"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65928

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 56,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56123

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 68,035"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68035

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 110,265"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110265

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 33,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33178
