[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SO PLATTE R. AT WATERTON, CO (3244) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "3244.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "3244-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 14,816"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14816

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 14,171"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14171

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 11,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11125

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 40,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40521

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 24,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24237

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 21,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21932

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 32,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32589

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 12,394"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12394

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 26,654"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26654

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 22,141"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22141

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 20,616"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20616

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 25,271"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25271

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 38,131"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38131

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 13,651"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13651
