[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BADGER CR. NR FT. MORGAN CO (3271) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "3271.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "3271-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 25,457"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25457

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 23,592"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23592

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 27,264"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27264

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 78,790"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78790

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 62,117"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62117

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 35,408"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35408

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 88,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88935

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 45,416"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45416

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 62,761"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62761

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 104,163"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104163

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 61,185"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61185

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 59,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59060

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 112,913"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112913

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 41,186"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41186
