[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BOX ELDER CR NR DENVER INT, CO (3288) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "3288.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "3288-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 29,138"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29138

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 33,686"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33686

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 39,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39509

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 112,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112004

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 63,241"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63241

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 61,319"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61319

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 84,229"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84229

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 42,981"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42981

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 63,166"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63166

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 62,180"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62180

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 55,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55966

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 67,343"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67343

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 124,201"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,124201

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 44,793"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44793
