[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SMOKY HILL RIVER NR RUSSEL SPRINGS KS (405) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "405.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "405-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 26,415"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26415

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 59,414"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59414

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 73,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73935

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 261,243"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,261243

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 128,128"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128128

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 74,827"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74827

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 162,998"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162998

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 99,593"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99593

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 75,911"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75911

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 142,711"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142711

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 97,044"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97044

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 78,895"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78895

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 195,811"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195811

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 52,853"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52853
