[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SMOKY HILL RIVER NR WESKAN KS (406) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "406.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "406-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 11,733"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11733

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 27,228"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27228

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 30,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30335

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 91,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91418

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 56,908"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56908

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 38,106"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38106

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 78,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78875

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 40,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40386

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 34,618"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34618

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 65,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65388

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 44,083"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44083

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 32,326"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32326

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 69,068"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69068

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 37,240"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37240
