[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LADDER CR. NR LEOTI KS (408) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "408.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "408-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 13,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13966

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 40,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40368

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 39,948"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39948

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 150,996"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,150996

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 69,321"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69321

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 40,538"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40538

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 91,939"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91939

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 53,617"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53617

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 48,655"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48655

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 85,728"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85728

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 56,496"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56496

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 46,684"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46684

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 94,923"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94923

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 39,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39559
