[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "S LADDER CR NR LEOTI KS (409) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "409.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "409-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 7,010"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7010

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 21,131"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21131

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 20,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20386

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 79,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79509

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 35,505"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35505

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 20,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20875

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 46,628"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46628

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 26,737"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26737

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 26,114"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26114

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 43,337"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43337

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 28,930"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28930

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 24,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24966

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 48,076"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48076

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 21,364"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21364
