[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARIKAREE RIVER NR JOES CO (505) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "505.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "505-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 96,674"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96674

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 140,050"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140050

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 106,666"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,106666

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 333,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,333754

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 253,289"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,253289

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 171,673"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171673

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 415,979"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,415979

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 227,348"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227348

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 229,173"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,229173

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 331,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331607

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 212,606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,212606

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 192,778"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192778

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 412,157"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,412157

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 148,629"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148629
