[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "NF REPUBLICAN RIVER NR SANBORN NE (506) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "506.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "506-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 14,593"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14593

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 15,615"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15615

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 14,287"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14287

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 43,193"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43193

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 32,793"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32793

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 24,150"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24150

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 50,167"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50167

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 26,437"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26437

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 18,292"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18292

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 52,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52472

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 38,815"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38815

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 34,585"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34585

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 53,904"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53904

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 22,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22087
