[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "S. F. REPUBLICAN RIVER ABOVE BONNY LAKE (550) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "550.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "550-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 27,685"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27685

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 46,983"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46983

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 40,109"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40109

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 148,299"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148299

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 100,684"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100684

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 68,721"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68721

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 169,785"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169785

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 87,136"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87136

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 66,043"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66043

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 127,962"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127962

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 81,646"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81646

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 77,583"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77583

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 141,752"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141752

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 52,407"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52407
