[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BASEFLOW AREA ABV 506 (551) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "551.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "551-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 131,798"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131798

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 147,756"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147756

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 122,603"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,122603

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 345,898"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,345898

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 290,324"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,290324

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 180,963"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180963

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 443,055"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,443055

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 242,443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,242443

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 221,347"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,221347

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 419,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,419469

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 285,937"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285937

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 272,385"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,272385

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 429,728"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,429728

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 173,248"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,173248
