[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FRENCHMAN CREEK ABV ENDERS RES (554) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "554.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "554-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 115,145"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,115145

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 149,475"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,149475

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 134,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134543

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 269,449"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,269449

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 265,532"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,265532

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 174,496"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174496

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 321,484"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,321484

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 172,748"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,172748

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 144,192"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,144192

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 366,661"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,366661

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 310,907"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,310907

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 199,798"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,199798

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 415,127"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,415127

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 156,184"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156184
