[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "MDL BEAVER CRK NEAR KANORADO KS (556) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "556.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "556-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 10,946"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10946

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 16,850"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16850

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 19,376"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19376

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 70,594"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70594

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 42,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42388

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 30,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30559

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 61,710"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61710

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 30,573"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30573

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 24,473"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24473

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 53,402"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53402

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 33,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33474

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 29,119"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29119

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 53,114"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53114

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 21,271"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21271
