[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BONNY CREEK NR BENKLEMAN NE (559) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "559.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "559-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 11,233"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11233

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 14,710"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14710

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 16,848"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16848

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 62,887"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62887

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 37,085"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37085

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 27,515"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27515

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 58,859"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58859

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 30,099"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30099

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 21,038"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21038

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 51,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51388

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 34,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34125

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 32,751"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32751

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 53,784"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53784

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 17,649"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17649
