[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR (ABEC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ABEC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ABEC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 50,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50509

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 55,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55837

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 78,531"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78531

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 93,551"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93551

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 100,661"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100661

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 79,302"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79302

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 80,436"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80436

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 121,893"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121893

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 72,696"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72696

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 80,073"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80073

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 110,868"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110868

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 114,042"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114042

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 104,363"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104363

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 94,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94808
