[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR (ABVC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ABVC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ABVC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 51,376"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51376

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 55,789"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55789

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 45,962"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45962

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 97,374"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97374

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 87,454"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87454

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 56,728"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56728

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 93,195"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93195

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 78,554"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78554

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 71,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71935

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 84,332"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84332

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 122,005"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,122005

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 127,535"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127535

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 121,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121804

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 80,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80757
