[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Avondale, CO (ADLC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ADLC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ADLC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 1,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1411

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 12,601"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12601

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 17,758"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17758

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 40,992"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40992

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 24,820"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24820

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 21,426"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21426

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 36,692"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36692

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 19,807"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19807

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 28,745"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28745

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 25,545"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25545

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 38,912"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38912

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 39,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39368

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 28,369"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28369

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 23,124"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23124
