[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Walnut Creek
 (AERK1N) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "AERK1N.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "AERK1N-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 53,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53565

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 146,364"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146364

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 131,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131368

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 604,446"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,604446

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 224,186"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,224186

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 125,968"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125968

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 327,694"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,327694

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 190,869"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190869

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 182,161"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182161

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 293,734"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,293734

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 210,843"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,210843

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 174,036"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174036

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 285,852"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285852

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 126,486"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126486
