[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE AT ALAMOSA, CO (ALAC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ALAC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ALAC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 10,714"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10714

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 4,934"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4934

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 6,195"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6195

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 15,165"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15165

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 24,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24465

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 16,653"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16653

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 20,183"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20183

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 6,318"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6318

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 11,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11875

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 14,307"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14307

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 17,600"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17600

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 14,550"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14550

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 22,825"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22825

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 20,747"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20747
