[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "EAST RIVER - AT ALMONT (ALEC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ALEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ALEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 259,876"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,259876

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 363,734"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,363734

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 304,994"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,304994

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 296,241"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,296241

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 408,856"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,408856

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 298,959"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,298959

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 271,225"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,271225

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 441,324"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,441324

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 228,845"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,228845

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 319,815"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,319815

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 353,480"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,353480

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 275,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275411

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 349,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,349418

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 416,446"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,416446
