[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TAYLOR RIVER - ALMONT (ALTC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ALTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 146,252"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146252

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 192,572"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192572

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 155,654"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,155654

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 166,952"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166952

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 223,303"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,223303

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 181,186"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,181186

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 171,453"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171453

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 244,892"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,244892

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 141,896"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141896

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 182,840"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182840

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 226,149"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,226149

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 209,169"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,209169

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 227,984"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227984

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 276,760"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,276760
