[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TAYLOR RIVER - ALMONT (ALTC2L_F) SNODAS SWE"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent, SWE (in)"
LeftYAxisLabelPrecision = "1"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2004]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2004"

[Data 1.2]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2005]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2005"

[Data 1.3]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2006]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2006"

[Data 1.4]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2007]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2007"

[Data 1.5]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2008]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2008"

[Data 1.6]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2009]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2009"

[Data 1.7]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2010]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2010"

[Data 1.8]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2011]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2011"

[Data 1.9]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2012]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2012"

[Data 1.10]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2013]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2013"

[Data 1.11]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2014]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2014"

[Data 1.12]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2015]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2015"

[Data 1.13]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2016]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2016"

[Data 1.14]

TSID = "ALTC2L_F.SNODAS.SWE.Day[2017]"
TSAlias = "ALTC2L_F-SNODAS-SWE-Day-2017"

Color = "Blue"
LineWidth = 3
