[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ROARING FORK - NR ASPEN (APNC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "APNC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "APNC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 85,489"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85489

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 113,015"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113015

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 125,840"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125840

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 137,201"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137201

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 163,020"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,163020

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 133,108"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133108

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 139,424"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139424

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 206,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,206597

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 113,854"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113854

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 134,550"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134550

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 174,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174559

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 166,809"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166809

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 172,349"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,172349

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 154,500"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154500
