[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Granite, CO (ARGC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ARGC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ARGC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 54,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54125

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 50,381"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50381

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 60,387"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60387

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 87,514"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87514

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 84,873"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84873

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 59,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59787

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 74,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74837

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 96,415"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96415

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 65,574"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65574

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 71,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71942

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 112,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112808

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 114,282"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114282

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 101,261"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101261

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 81,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81297
