[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR (ARNC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ARNC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ARNC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 54,468"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54468

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 58,782"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58782

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 38,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38418

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 116,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,116589

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 107,868"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107868

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 51,361"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51361

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 112,915"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112915

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 56,819"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56819

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 65,629"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65629

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 77,627"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77627

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 110,884"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110884

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 105,581"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105581

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 108,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108178

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 68,203"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68203
