[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Colo Baker Gulch Lower (BAKC2LO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BAKC2LO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BAKC2LO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16098

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 20,171"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20171

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 22,447"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22447

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 29,742"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29742

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 31,403"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31403

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 30,041"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30041

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 27,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27388

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 48,568"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48568

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 22,781"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22781

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 29,443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29443

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 37,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37966

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 30,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30589

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 39,254"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39254

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 36,031"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36031
