[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BADGER CRK (BCHC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BCHC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BCHC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 50,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50976

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 59,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59668

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 32,334"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32334

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 101,228"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101228

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 89,145"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89145

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 53,907"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53907

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 116,116"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,116116

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 46,149"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46149

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 63,789"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63789

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 70,360"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70360

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 105,936"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105936

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 112,931"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112931

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 104,746"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104746

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 51,291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51291
