[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - BLUE MESA RESERVOIR (BMDC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BMDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BMDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 421,963"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,421963

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 482,997"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,482997

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 522,003"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,522003

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 525,904"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,525904

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 737,348"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,737348

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 601,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,601787

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 650,956"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,650956

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 783,773"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,783773

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 499,455"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,499455

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 566,904"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,566904

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 824,967"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,824967

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 742,870"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,742870

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 802,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,802200

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 878,390"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,878390
