[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "HUERFANO RVR (BONC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BONC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BONC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 10,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10804

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 45,027"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45027

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 48,080"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48080

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 134,577"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134577

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 87,126"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87126

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 63,505"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63505

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 123,342"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,123342

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 58,973"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58973

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 108,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108668

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 66,568"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66568

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 88,082"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88082

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 87,953"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87953

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 85,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85215

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 71,708"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71708
