[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "HUERFANO RVR UP ELEV (BONC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BONC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BONC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 341,872"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,341872

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 547,600"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,547600

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 336,823"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,336823

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 854,856"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,854856

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 669,905"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,669905

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 559,951"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,559951

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 911,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,911507

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 431,118"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,431118

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 643,896"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,643896

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 447,623"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,447623

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 544,402"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,544402

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 654,119"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,654119

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 598,515"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,598515

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 438,236"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,438236
