[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTABESCO >8000ft - <10,250ft (BTABESM) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTABESM.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTABESM-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 45,032"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45032

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 53,202"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53202

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 43,258"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43258

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 71,074"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71074

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 60,045"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60045

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 56,484"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56484

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 59,005"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59005

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 78,183"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78183

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 49,903"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49903

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 71,770"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71770

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 88,068"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88068

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 90,143"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90143

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 95,969"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95969

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 83,560"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83560
