[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTABESCO >10,250ft (BTABESUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTABESUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTABESUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 82,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82223

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 87,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87837

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 79,650"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79650

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 103,766"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103766

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 104,795"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104795

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 92,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92422

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 89,218"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89218

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 145,646"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145646

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 78,694"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78694

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 101,464"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101464

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 114,670"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114670

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 118,972"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118972

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 113,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113681

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 92,906"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92906
