[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTABESCO <8000ft (BTABESLO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTABESLO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTABESLO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 2,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2621

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 3,793"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3793

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 2,124"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2124

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 5,454"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5454

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 4,216"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4216

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 4,230"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4230

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 5,382"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5382

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 4,900"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4900

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 4,014"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4014

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 7,360"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7360

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 6,799"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6799

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 6,023"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6023

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 6,655"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6655

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 5,443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5443
