[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTCANYCO >10,250ft (BTCANYUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTCANYUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTCANYUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 9,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9499

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 11,708"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11708

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 7,891"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7891

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 16,708"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16708

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 12,693"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12693

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 13,934"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13934

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 18,311"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18311

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 13,356"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13356

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 13,934"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13934

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 24,933"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24933

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 23,902"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23902

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 25,915"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25915

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 27,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27470

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 17,781"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17781
