[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTCANYCO <8000ft (BTCANYLO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTCANYLO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTCANYLO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 10,556"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10556

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 14,775"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14775

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 10,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10418

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 26,798"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26798

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 17,341"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17341

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 18,363"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18363

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 32,216"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32216

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 13,488"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13488

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 19,323"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19323

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 44,394"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44394

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 33,148"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33148

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 32,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32565

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 37,358"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37358

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 22,079"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22079
