[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTNFDRCO <8000ft (BTNFDRLO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTNFDRLO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTNFDRLO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 5,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5125

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 6,373"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6373

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 4,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4386

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 11,459"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11459

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 7,191"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7191

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 7,968"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7968

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 13,473"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13473

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 6,080"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6080

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 8,376"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8376

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 18,652"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18652

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 13,473"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13473

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 13,209"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13209

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 15,835"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15835

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 9,270"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9270
