[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTNFDRCO >10,250ft (BTNFDRUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTNFDRUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTNFDRUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,020"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16020

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 19,644"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19644

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 16,081"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16081

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 25,269"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25269

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 24,680"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24680

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 22,637"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22637

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 24,703"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24703

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 36,080"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36080

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 20,865"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20865

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 26,704"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26704

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 32,283"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32283

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 37,730"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37730

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 32,373"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32373

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 22,699"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22699
