[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BTNFDRCO >8000ft - <10,250ft (BTNFDRM) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BTNFDRM.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BTNFDRM-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 21,642"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21642

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 25,071"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25071

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 17,319"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17319

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 35,598"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35598

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 28,102"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28102

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 29,899"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29899

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 38,326"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38326

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 36,973"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36973

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 29,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29237

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 48,343"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48343

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 49,147"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49147

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 59,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59757

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 61,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61004

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 36,694"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36694
