[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BLUE - BLUE RIVER (BUEC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "BUEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "BUEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 39,545"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39545

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 50,969"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50969

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 60,485"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60485

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 58,173"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58173

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 61,370"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61370

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 51,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51469

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 49,700"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49700

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 83,963"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83963

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 49,174"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49174

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 52,092"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52092

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 78,304"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78304

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 74,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74065

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 79,392"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79392

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 50,255"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50255
