[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COLORADO - NR CAMEO (CAMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CAMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CAMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 323,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,323717

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 594,091"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,594091

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 581,172"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,581172

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 499,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,499875

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 930,806"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,930806

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 674,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,674837

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 868,696"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,868696

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 961,709"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,961709

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 710,364"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,710364

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 797,773"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,797773

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,085,352"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1085352

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 783,300"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,783300

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,233,692"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1233692

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 876,984"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,876984
