[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COLORADO - NR GRANBY AT WINDY GAP (CAWC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CAWC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CAWC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 15,865"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15865

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 21,585"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21585

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 19,643"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19643

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 25,884"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25884

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 30,345"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30345

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 27,779"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27779

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 25,818"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25818

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 39,527"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39527

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 25,847"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25847

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 26,641"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26641

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 36,028"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36028

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 26,758"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26758

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 29,148"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29148

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 32,221"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32221
