[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COTTONWOOD CRK (CBVC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CBVC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CBVC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 9,013"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9013

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 11,057"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11057

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 9,812"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9812

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 22,967"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22967

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 21,011"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21011

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 14,549"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14549

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 23,088"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23088

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 18,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18151

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 16,645"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16645

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 21,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21098

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 31,715"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31715

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 33,530"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33530

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 31,560"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31560

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 22,292"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22292
