[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLAFTCCO >10,250ft (CLAFTCUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLAFTCUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLAFTCUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 129,143"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129143

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 170,643"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,170643

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 164,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164787

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 206,204"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,206204

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 218,487"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,218487

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 206,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,206597

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 205,157"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,205157

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 316,464"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,316464

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 156,362"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156362

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 205,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,205065

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 280,649"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,280649

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 245,194"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,245194

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 245,451"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,245451

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 198,994"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,198994
