[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLAFTCCO <8000ft (CLAFTCLO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLAFTCLO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLAFTCLO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,042"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16042

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 23,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23060

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 23,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23681

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 56,903"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56903

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 39,433"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39433

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 46,814"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46814

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 72,710"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72710

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 34,420"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34420

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 45,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45474

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 92,725"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92725

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 74,364"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74364

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 72,055"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72055

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 87,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87472

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 41,106"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41106
