[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLAFTCCO >8000ft - <10,250ft (CLAFTCM) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLAFTCM.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLAFTCM-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 105,953"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105953

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 134,959"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134959

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 126,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126565

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 214,183"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214183

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 186,369"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,186369

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 194,904"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,194904

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 233,526"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,233526

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 270,445"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,270445

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 167,032"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,167032

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 243,516"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,243516

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 330,822"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,330822

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 331,488"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331488

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 338,021"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,338021

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 256,158"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,256158
