[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLANSECO >8000ft - <10,250ft (CLANSEM) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLANSEM.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLANSEM-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 67,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67004

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 75,722"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75722

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 69,421"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69421

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 147,339"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147339

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 154,755"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154755

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 159,242"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,159242

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 216,298"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,216298

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 179,214"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,179214

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 146,034"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146034

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 197,101"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,197101

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 244,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,244589

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 275,527"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275527

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 344,115"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,344115

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 171,664"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171664
