[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLANSECO >10,250ft (CLANSEUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLANSEUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLANSEUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 8,949"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8949

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 10,049"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10049

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 9,739"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9739

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 10,928"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10928

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 12,605"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12605

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 11,843"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11843

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 13,968"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13968

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 16,039"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16039

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 8,772"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8772

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 11,274"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11274

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 21,562"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21562

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 18,796"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18796

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 19,350"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19350

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 14,109"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14109
