[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLANSECO <8000ft (CLANSELO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLANSELO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLANSELO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 46,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46787

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 59,740"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59740

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 60,169"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60169

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 110,114"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110114

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 114,488"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114488

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 113,431"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113431

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 184,230"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,184230

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 103,296"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103296

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 102,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,102434

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 206,271"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,206271

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 200,211"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,200211

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 171,791"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171791

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 210,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,210470

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 98,769"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98769
