[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "UNCOMPAHGRE - COLONA (CLOC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 88,840"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88840

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 104,814"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104814

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 97,324"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97324

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 104,231"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104231

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 148,085"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148085

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 113,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113565

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 131,614"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131614

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 133,944"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133944

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 101,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101808

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 124,414"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,124414

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 140,426"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140426

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 148,257"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148257

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 167,338"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,167338

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 136,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,136543
