[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLOSED BASIN (close) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "close.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "close-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 688,218"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,688218

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 445,817"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,445817

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 246,001"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,246001

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 721,285"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,721285

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 824,679"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,824679

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 652,573"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,652573

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 929,766"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,929766

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 474,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,474575

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 591,012"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,591012

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 641,636"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,641636

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 863,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,863999

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 757,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,757681

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,101,306"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1101306

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 798,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,798087
