[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CLEAR CRK RES (CLRC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLRC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLRC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 535"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,535

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 638"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,638

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,443

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 868"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,868

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 867"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,867

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 569"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,569

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 891"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,891

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 751"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,751

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,607

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 868"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,868

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,309"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1309

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 1,340"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1340

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,109"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1109

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 969"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,969
