[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - CRYSTAL RESERVOIR (CLSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CLSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CLSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 143,463"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143463

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 175,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,175754

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 166,494"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166494

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 169,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169422

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 253,739"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,253739

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 201,662"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,201662

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 225,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,225151

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 264,501"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,264501

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 164,650"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164650

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 198,180"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,198180

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 277,696"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,277696

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 220,515"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,220515

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 263,008"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,263008

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 243,109"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,243109
