[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Canon City, CO (CNCC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CNCC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CNCC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 50,941"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50941

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 58,777"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58777

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 46,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46090

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 114,221"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114221

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 94,112"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94112

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 67,697"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67697

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 126,364"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126364

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 39,341"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39341

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 79,082"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79082

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 59,884"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59884

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 78,317"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78317

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 90,130"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90130

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 85,600"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85600

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 44,096"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44096
