[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Coolidge, KS (COOK1) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "COOK1.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "COOK1-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 23,134"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23134

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 151,379"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,151379

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 117,212"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,117212

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 675,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,675125

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 162,536"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162536

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 123,878"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,123878

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 342,517"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,342517

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 129,206"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129206

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 247,334"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,247334

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 186,356"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,186356

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 196,729"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,196729

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 220,652"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,220652

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 276,729"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,276729

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 160,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160237
