[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COCHETOPA CREEK - BLO ROCK CK NR PARLIN (CRCC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CRCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CRCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 177,043"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,177043

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 152,552"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,152552

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 165,882"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,165882

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 219,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,219976

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 229,713"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,229713

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 214,085"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214085

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 247,496"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,247496

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 227,172"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227172

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 186,616"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,186616

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 199,504"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,199504

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 316,134"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,316134

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 300,850"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,300850

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 311,003"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,311003

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 274,427"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274427
