[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE AT THIRTYMILE BRIDGE, NR CREEDE, CO. (CRDC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CRDC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CRDC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 223,450"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,223450

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 289,591"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,289591

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 202,426"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,202426

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 208,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,208151

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 286,126"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,286126

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 238,104"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,238104

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 212,225"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,212225

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 292,961"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,292961

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 205,118"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,205118

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 185,542"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,185542

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 262,049"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,262049

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 255,677"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255677

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 258,745"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,258745

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 239,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,239676
