[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CROSS CREEK - NR MINTURN (CSSC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "CSSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "CSSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 27,351"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27351

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 38,231"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38231

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 47,043"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47043

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 48,095"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48095

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 59,218"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59218

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 45,002"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45002

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 39,355"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39355

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 71,678"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71678

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 38,412"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38412

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 45,961"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45961

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 72,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72465

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 63,986"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63986

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 58,049"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58049

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 53,244"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53244
