[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "DOLORES - NR BEDROCK (DBDC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DBDC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DBDC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 198,486"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,198486

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 213,451"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,213451

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 207,571"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,207571

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 191,914"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191914

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 418,737"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,418737

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 337,996"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,337996

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 492,432"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,492432

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 350,475"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,350475

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 398,964"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,398964

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 363,907"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,363907

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 307,843"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,307843

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 362,282"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,362282

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 614,743"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,614743

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 334,978"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,334978
