[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - DELTA (DELC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DELC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DELC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 390,286"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,390286

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 589,266"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,589266

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 427,241"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,427241

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 438,902"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,438902

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 672,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,672754

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 526,558"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,526558

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 627,917"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,627917

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 599,298"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,599298

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 469,777"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,469777

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 505,554"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,505554

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 556,274"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,556274

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 389,494"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,389494

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 700,276"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,700276

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 601,772"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,601772
