[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ANIMAS - Durango Pump Plant Lake Knighthorse (DGOC2R_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DGOC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DGOC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 29,839"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29839

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 43,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43422

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 24,046"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24046

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 24,104"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24104

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 63,256"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63256

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 34,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34575

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 49,519"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49519

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 36,156"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36156

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 45,541"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45541

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 40,141"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40141

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 28,180"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28180

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 38,566"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38566

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 72,208"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72208

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 68,111"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68111
