[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BLUE - DILLON RESERVOIR (DIRC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DIRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DIRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 36,695"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36695

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 43,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43875

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 59,720"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59720

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 55,067"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55067

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 61,117"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61117

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 57,640"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57640

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 52,539"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52539

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 77,722"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77722

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 45,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45499

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 58,331"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58331

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 85,187"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85187

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 78,892"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78892

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 82,102"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82102

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 61,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61123
