[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "UNCOMPAHGRE - AT DELTA (DLAC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DLAC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DLAC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 141,042"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141042

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 114,736"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114736

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 123,356"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,123356

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 180,610"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180610

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 263,463"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,263463

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 185,455"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,185455

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 274,606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274606

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 176,254"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,176254

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 173,909"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,173909

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 279,389"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,279389

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 284,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,284543

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 236,316"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,236316

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 360,235"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,360235

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 248,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,248499
