[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE NEAR DEL NORTE, CO (DNRC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DNRC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DNRC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 356,596"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,356596

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 246,445"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,246445

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 165,922"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,165922

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 241,339"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,241339

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 332,189"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,332189

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 255,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255499

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 285,794"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285794

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 244,674"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,244674

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 245,878"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,245878

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 197,378"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,197378

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 363,291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,363291

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 297,332"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,297332

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 339,466"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,339466

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 280,140"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,280140
