[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "DOLORES - NR CISCO (DOLU1L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DOLU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DOLU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 135,700"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,135700

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 218,588"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,218588

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 167,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,167942

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 182,381"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182381

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 372,475"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,372475

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 303,994"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,303994

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 447,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,447200

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 348,876"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,348876

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 331,208"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331208

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 370,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,370297

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 310,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,310004

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 303,569"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,303569

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 580,433"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,580433

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 287,156"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,287156
