[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ANIMAS - DURANGO (DRGC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 632,833"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,632833

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 983,498"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,983498

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 623,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,623125

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 658,078"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,658078

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 973,118"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,973118

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 760,568"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,760568

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 774,030"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,774030

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 1,059,022"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1059022

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 768,510"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,768510

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 695,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,695942

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 896,268"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,896268

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 933,320"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,933320

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,046,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1046388

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 989,749"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,989749
