[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "DOLORES - BLO RICO (DRRC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DRRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DRRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 110,733"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110733

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 151,761"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,151761

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 112,380"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112380

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 115,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,115072

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 170,923"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,170923

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 144,110"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,144110

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 139,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139297

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 203,210"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,203210

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 139,043"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139043

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 125,220"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125220

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 174,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174589

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 199,989"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,199989

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 191,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191787

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 197,684"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,197684
