[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GRAPE CRK (DWSC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "DWSC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "DWSC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 4,785"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4785

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 3,759"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3759

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 2,982"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2982

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 7,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7999

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 6,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6999

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 4,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4797

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 8,005"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8005

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 2,591"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2591

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 5,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5386

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 3,707"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3707

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 5,191"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5191

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 6,183"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6183

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 6,154"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6154

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 3,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3033
