[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COLORADO - NR DOTSERO (EGLC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "EGLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "EGLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 374,630"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,374630

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 435,259"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,435259

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 460,086"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,460086

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 529,743"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,529743

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 662,743"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,662743

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 590,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,590098

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 544,825"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,544825

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 893,382"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,893382

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 441,222"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,441222

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 538,888"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,538888

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 915,001"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,915001

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 694,336"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,694336

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 836,524"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,836524

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 667,830"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,667830
