[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ELKHEAD CK - LONG GULCH, ABV, HAYDEN, NR (ELHC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ELHC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ELHC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 62,404"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62404

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 128,349"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128349

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 106,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,106607

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 126,813"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126813

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 179,625"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,179625

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 158,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,158411

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 160,535"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160535

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 237,042"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,237042

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 134,414"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134414

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 137,006"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137006

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 203,107"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,203107

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 152,648"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,152648

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 245,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,245976

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 202,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,202717
