[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ELK - NR MILNER (ENMC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ENMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ENMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 405,712"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,405712

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 546,429"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,546429

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 517,175"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,517175

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 526,189"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,526189

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 668,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,668087

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 591,337"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,591337

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 565,387"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,565387

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 932,603"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,932603

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 468,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,468470

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 450,083"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,450083

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 879,977"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,879977

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 591,587"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,591587

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 866,884"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,866884

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 721,528"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,721528
