[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FOURMILE CRK (FCAC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FCAC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FCAC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 108,292"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108292

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 127,946"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127946

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 92,127"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92127

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 259,658"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,259658

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 164,476"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164476

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 156,724"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156724

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 243,649"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,243649

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 109,355"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109355

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 160,510"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160510

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 153,790"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153790

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 157,198"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,157198

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 208,083"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,208083

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 217,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,217472

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 125,517"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125517
