[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fountain Creek at Pueblo, CO (FCHC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FCHC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FCHC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 495"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,495

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 5,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5465

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 7,075"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7075

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 15,710"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15710

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 9,926"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9926

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 9,742"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9742

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 15,384"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15384

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 7,444"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7444

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 10,770"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10770

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 10,054"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10054

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 15,100"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15100

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 14,997"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14997

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 12,683"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12683

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 9,203"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9203
