[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fountain Creek nr Fountain, CO (FHAC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FHAC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FHAC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 3,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3388

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 9,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9808

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 8,541"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8541

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 23,240"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23240

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 16,751"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16751

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 17,003"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17003

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 28,092"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28092

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 11,144"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11144

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 19,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19681

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 15,595"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15595

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 18,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18060

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 20,581"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20581

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 29,020"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29020

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 14,136"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14136
