[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FISH CREEK - UPPER STN NR STEAMBOAT SPRINGS (FISC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FISC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FISC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 51,794"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51794

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 57,456"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57456

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 57,768"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57768

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 43,567"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43567

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 54,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54469

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 46,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46335

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 44,918"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44918

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 81,997"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81997

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 34,082"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34082

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 38,438"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38438

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 79,077"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79077

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 48,660"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48660

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 70,679"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70679

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 55,936"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55936
