[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fountain Creek at Colorado Springs, CO (FNEC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FNEC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FNEC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 52,449"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52449

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 77,453"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77453

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 65,015"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65015

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 178,169"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,178169

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 106,779"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,106779

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 121,817"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121817

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 170,615"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,170615

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 69,866"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69866

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 99,533"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99533

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 108,137"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108137

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 103,413"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103413

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 141,619"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141619

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 202,283"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,202283

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 90,829"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90829
