[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FRYING PAN - NR THOMASVILLE (FPTC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FPTC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FPTC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 93,071"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93071

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 126,882"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126882

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 171,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171335

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 171,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171033

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 218,400"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,218400

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 160,704"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160704

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 158,267"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,158267

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 257,016"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,257016

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 140,699"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140699

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 161,096"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,161096

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 232,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,232808

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 225,486"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,225486

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 212,389"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,212389

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 188,176"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188176
