[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fraser - NCWCD Lower (FRASER-L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FRASER-L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FRASER-L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 72,939"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72939

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 99,305"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99305

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 98,138"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98138

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 116,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,116422

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 124,677"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,124677

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 122,198"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,122198

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 126,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126754

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 157,846"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,157846

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 107,682"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107682

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 111,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,111942

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 170,682"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,170682

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 145,483"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145483

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 142,440"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142440

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 148,176"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148176
