[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fraser - NCWCD Upper (FRASER-U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FRASER-U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FRASER-U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 39,155"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39155

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 51,502"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51502

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 52,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52090

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 61,276"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61276

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 58,720"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58720

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 58,403"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58403

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 57,463"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57463

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 89,198"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89198

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 51,692"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51692

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 55,628"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55628

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 86,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86223

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 77,387"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77387

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 77,492"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77492

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 70,100"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70100
