[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FOUNTAIN CRK (FSEC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FSEC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FSEC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 2,863"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2863

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 5,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5178

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 4,953"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4953

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 14,798"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14798

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 9,295"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9295

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 10,564"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10564

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 17,213"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17213

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 6,502"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6502

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 10,618"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10618

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 9,337"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9337

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 9,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9521

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 11,402"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11402

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 16,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16681

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 7,405"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7405
