[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "APISHAPA RVR UP ELEV (FWRC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "FWRC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "FWRC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 69,829"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69829

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 204,377"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,204377

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 97,598"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97598

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 313,974"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,313974

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 192,690"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192690

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 160,747"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160747

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 284,455"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,284455

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 131,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131932

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 195,387"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195387

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 131,029"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131029

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 126,895"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,126895

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 172,992"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,172992

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 208,230"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,208230

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 167,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,167472
