[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Lake Granby Upper (GBYC2UP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GBYC2UP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GBYC2UP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 51,117"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51117

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 55,447"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55447

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 52,615"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52615

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 60,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60335

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 55,210"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55210

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 54,466"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54466

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 57,058"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57058

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 94,938"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94938

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 54,734"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54734

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 59,168"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59168

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 74,293"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74293

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 71,024"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71024

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 82,202"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82202

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 61,629"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61629
