[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Lake Granby (GBYC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GBYC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GBYC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 2,718"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2718

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 3,666"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3666

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 3,630"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3630

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 4,706"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4706

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 5,497"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5497

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 5,176"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5176

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 5,094"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5094

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 7,624"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7624

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 5,603"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5603

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 5,257"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5257

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 8,897"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8897

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 4,431"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4431

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 5,652"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5652

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 6,235"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,6235
