[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Lake Granby Lower (GBYC2LO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GBYC2LO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GBYC2LO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 42,020"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42020

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 52,309"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52309

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 48,443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48443

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 61,975"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61975

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 63,545"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63545

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 65,882"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65882

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 65,009"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65009

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 100,202"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100202

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 60,207"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60207

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 64,572"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64572

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 87,848"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87848

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 69,698"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69698

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 90,056"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90056

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 90,490"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90490
