[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR (GCKK1) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GCKK1.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GCKK1-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 4,793"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4793

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 8,655"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8655

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 8,133"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8133

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 45,384"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45384

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 12,078"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12078

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 7,569"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7569

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 15,796"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15796

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 9,835"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9835

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 14,269"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14269

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 18,256"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18256

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 20,268"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20268

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 15,861"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15861

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 17,487"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17487

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 8,592"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8592
