[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COLORADO - BLO GLENWOOD SPRS (GCOC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GCOC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GCOC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 90,603"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90603

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 107,795"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107795

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 106,904"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,106904

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 96,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96335

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 153,917"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153917

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 120,894"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,120894

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 121,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121521

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 188,481"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188481

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 98,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98098

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 111,570"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,111570

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 190,019"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190019

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 140,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140151

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 184,969"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,184969

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 159,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,159200
