[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GRAPE CRK (GCWC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GCWC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GCWC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 160,576"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160576

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 175,665"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,175665

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 109,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109065

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 248,625"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,248625

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 222,403"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222403

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 195,628"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195628

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 259,956"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,259956

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 127,016"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127016

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 190,000"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190000

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 149,977"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,149977

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 223,528"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,223528

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 213,554"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,213554

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 270,188"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,270188

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 162,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162676
