[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - NR GRAND JUNCTION (GJNC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GJNC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GJNC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 259,923"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,259923

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 373,683"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,373683

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 247,238"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,247238

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 281,650"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,281650

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 490,131"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,490131

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 355,012"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,355012

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 460,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,460499

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 418,975"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,418975

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 410,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,410621

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 470,861"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,470861

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 502,667"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,502667

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 338,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,338087

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 761,557"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,761557

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 465,687"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,465687
