[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BLUE - GREEN MT RESERVOIR (GMRC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GMRC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GMRC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 154,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154621

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 168,681"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,168681

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 212,310"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,212310

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 235,489"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,235489

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 264,286"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,264286

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 231,793"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,231793

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 190,680"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190680

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 331,348"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331348

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 181,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,181411

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 247,809"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,247809

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 367,462"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,367462

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 328,564"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,328564

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 312,990"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,312990

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 283,973"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,283973
