[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "EAGLE - BLO GYPSUM (GPSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 249,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,249717

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 292,191"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,292191

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 301,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,301561

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 364,130"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,364130

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 460,979"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,460979

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 380,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,380469

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 319,637"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,319637

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 484,491"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,484491

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 276,687"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,276687

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 402,031"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,402031

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 647,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,647368

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 523,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,523668

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 488,275"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,488275

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 473,262"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,473262
