[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Grand River Ditch (GRDC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GRDC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GRDC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 17,768"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17768

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 25,905"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25905

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 30,157"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30157

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 31,367"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31367

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 38,075"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38075

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 31,315"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31315

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 28,675"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28675

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 50,923"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50923

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 23,610"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23610

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 28,560"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28560

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 33,272"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33272

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 27,749"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27749

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 31,322"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31322

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 25,525"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25525
