[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GORE CK - VAIL RED SANDSTONE CK ABV (GRVC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GRVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GRVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 54,889"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54889

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 68,010"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68010

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 83,326"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83326

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 91,939"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91939

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 103,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103676

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 83,593"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83593

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 70,335"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70335

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 133,058"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133058

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 70,605"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70605

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 94,163"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94163

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 130,773"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,130773

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 114,975"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114975

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 112,199"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112199

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 103,176"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103176
