[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - NR GUNNISON (GUSC2L_F) SNODAS SWE Volume 1-Week Change"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume 1-Week Change (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2004]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2004"


[Data 1.2]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2005]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2005"


[Data 1.3]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2006]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2006"


[Data 1.4]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2007]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2007"


[Data 1.5]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2008]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2008"


[Data 1.6]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2009]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2009"


[Data 1.7]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2010]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2010"


[Data 1.8]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2011]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2011"


[Data 1.9]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2012]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2012"


[Data 1.10]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2013]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2013"


[Data 1.11]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2014]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2014"


[Data 1.12]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2015]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2015"


[Data 1.13]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2016]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2016"


[Data 1.14]

TSID = "GUSC2L_F.SNODAS.SWE-Volume-1WeekChange.Day[2017]"
TSAlias = "GUSC2L_F-SNODAS-SWE-Volume-1WeekChange-Day-2017"

Color = "Blue"
LineWidth = 3

