[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ROARING FORK - GLENWOOD SPRINGS (GWSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "GWSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "GWSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 562,062"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,562062

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 786,957"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,786957

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 754,015"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,754015

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 765,455"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,765455

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 1,020,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1020509

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 745,030"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,745030

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 762,137"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,762137

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 1,012,299"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1012299

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 601,205"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,601205

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 774,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,774065

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,231,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1231004

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 995,375"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,995375

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 949,931"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,949931

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 960,768"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,960768
