[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "HALFMOON CRK (HMCC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "HMCC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "HMCC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,323"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16323

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 19,588"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19588

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 25,530"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25530

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 29,492"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29492

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 33,407"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33407

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 27,318"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27318

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 28,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28932

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 44,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44434

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 26,549"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26549

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 28,915"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28915

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 41,579"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41579

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 43,707"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43707

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 36,429"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36429

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 31,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31509
