[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "HOMESTAKE CK - GOLD PARK (HMSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "HMSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "HMSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 26,053"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26053

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 31,455"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31455

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 42,604"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42604

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 43,743"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43743

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 52,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52757

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 41,437"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41437

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 36,142"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36142

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 64,975"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64975

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 34,897"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34897

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 39,429"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39429

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 54,646"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54646

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 49,620"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49620

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 48,347"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48347

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 43,269"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43269
