[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "HUERFANO RVR (HMZC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "HMZC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "HMZC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 28,533"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28533

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 31,300"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31300

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 13,826"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13826

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 34,266"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34266

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 41,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41223

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 33,827"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33827

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 37,862"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37862

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 20,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20123

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 26,995"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26995

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 24,262"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24262

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 34,404"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34404

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 31,039"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31039

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 41,330"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41330

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 28,849"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28849
