[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GREEN - NR JENSEN (JESU1L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "JESU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "JESU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 191,519"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191519

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 357,492"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,357492

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 299,599"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,299599

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 495,445"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,495445

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 718,282"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,718282

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 394,761"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,394761

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 397,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,397976

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 647,167"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,647167

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 545,274"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,545274

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 989,120"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,989120

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 868,493"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,868493

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 514,558"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,514558

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,035,816"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1035816

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 870,332"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,870332
