[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "JOHN MARTIN DAM (JMCC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "JMCC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "JMCC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 20,831"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20831

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 84,569"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84569

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 73,133"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73133

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 310,557"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,310557

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 113,817"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113817

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 93,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93717

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 214,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214543

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 81,761"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81761

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 145,165"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145165

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 109,983"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109983

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 95,589"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95589

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 153,190"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153190

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 101,446"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101446

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 119,922"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,119922
