[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Kendall
 (KENK1) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "KENK1.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "KENK1-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 3,775"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3775

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 16,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16123

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 13,372"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13372

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 81,765"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81765

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 17,944"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17944

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 12,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12033

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 26,991"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26991

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 14,216"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14216

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 17,629"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17629

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 21,995"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21995

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 25,730"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25730

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 19,642"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19642

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 26,967"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26967

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 10,183"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10183
