[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Cimarron River (OK) at Kenton (KENO2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "KENO2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "KENO2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 57,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57507

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 251,691"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,251691

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 99,880"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99880

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 516,397"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,516397

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 179,745"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,179745

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 215,362"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,215362

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 339,462"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,339462

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 131,832"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131832

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 258,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,258411

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 160,288"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160288

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 120,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,120935

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 275,831"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275831

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 270,541"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,270541

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 195,329"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195329
