[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "COLORADO - NR KREMMLING (KRMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "KRMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "KRMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 180,616"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180616

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 227,078"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227078

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 231,008"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,231008

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 267,294"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,267294

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 348,695"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,348695

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 286,863"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,286863

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 225,697"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,225697

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 437,688"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,437688

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 218,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,218418

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 309,748"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,309748

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 438,775"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,438775

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 398,441"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,398441

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 434,285"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,434285

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 414,146"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,414146
