[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BIG SANDY CRK (LAMC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LAMC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LAMC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 89,040"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89040

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 260,195"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260195

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 260,330"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260330

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 912,848"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,912848

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 504,920"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,504920

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 379,405"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,379405

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 857,239"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,857239

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 370,356"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,370356

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 414,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,414297

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 572,066"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,572066

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 434,903"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,434903

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 407,057"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,407057

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 651,900"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,651900

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 357,970"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,357970
