[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "BIG SANDY CRK UP ELEV (LAMC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LAMC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LAMC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 44,724"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44724

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 57,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57507

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 66,141"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66141

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 211,657"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,211657

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 117,278"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,117278

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 88,580"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88580

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 161,828"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,161828

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 69,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69559

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 110,088"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110088

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 113,428"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113428

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 86,390"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86390

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 76,814"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76814

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 181,672"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,181672

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 81,541"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81541
