[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR (LARC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LARC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LARC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 47,082"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47082

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 164,658"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164658

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 173,694"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,173694

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 578,395"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,578395

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 285,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285561

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 215,047"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,215047

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 560,056"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,560056

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 192,978"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192978

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 256,703"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,256703

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 275,830"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275830

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 274,830"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274830

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 315,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,315942

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 318,540"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,318540

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 231,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,231472
