[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ARKANSAS RVR UP ELEV (LARC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LARC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LARC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 18,099"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18099

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 26,466"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26466

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 29,378"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29378

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 95,712"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95712

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 55,508"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55508

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 46,683"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46683

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 81,310"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81310

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 31,769"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31769

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 53,953"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53953

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 49,949"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49949

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 41,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41470

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 37,994"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37994

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 89,296"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89296

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 37,392"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37392
