[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LOST CANYON CREEK - NR DOLORES (LCCC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 36,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36200

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 63,389"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63389

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 28,347"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28347

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 27,540"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27540

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 63,159"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63159

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 41,084"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41084

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 50,077"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50077

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 46,079"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46079

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 48,761"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48761

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 43,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43804

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 36,229"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36229

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 43,978"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43978

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 78,666"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78666

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 77,821"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77821
