[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Leadville, CO (LEDC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LEDC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LEDC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 91,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91087

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 95,119"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95119

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 146,876"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146876

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 147,943"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147943

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 166,958"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166958

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 134,032"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134032

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 114,362"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114362

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 192,598"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192598

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 113,355"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113355

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 118,827"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118827

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 162,901"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162901

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 147,359"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147359

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 169,361"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169361

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 133,120"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133120
