[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "FLORIDA - LEMON RES NR DURANGO (LEMC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LEMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LEMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 76,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76607

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 129,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129561

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 55,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55297

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 69,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69607

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 108,338"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108338

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 74,689"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74689

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 76,413"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76413

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 107,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107474

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 77,369"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77369

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 70,450"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70450

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 85,876"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85876

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 79,789"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79789

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 109,807"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109807

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 105,940"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105940
