[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LITTLE SNAKE - NR LILY (LILC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LILC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LILC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 243,930"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,243930

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 377,081"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,377081

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 450,637"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,450637

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 694,989"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,694989

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 1,175,201"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1175201

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 635,640"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,635640

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 688,683"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,688683

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 1,090,907"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1090907

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 634,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,634072

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 1,190,408"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1190408

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,364,241"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1364241

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 728,394"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,728394

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,416,696"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1416696

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 1,101,691"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1101691
