[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LITTLE NAVAJO OSO DIV DAM BLO CHROMO NR (LNAC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LNAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LNAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 18,018"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18018

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 23,614"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23614

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 11,246"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11246

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 16,545"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16545

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 30,728"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30728

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 23,193"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23193

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 24,332"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24332

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 23,056"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23056

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 20,423"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20423

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 17,227"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17227

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 15,642"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15642

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 16,662"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16662

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 22,948"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22948

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 27,331"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27331
