[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE NEAR LOBATOS, CO (LOBC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LOBC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LOBC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 78,174"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78174

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 82,870"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82870

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 43,910"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43910

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 83,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83422

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 83,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83932

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 101,058"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101058

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 131,173"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131173

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 56,823"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56823

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 59,894"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59894

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 70,985"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70985

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 76,985"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76985

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 76,100"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76100

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 89,007"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89007

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 92,284"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92284
