[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LOS PINOS - AT LA BOCA (LOSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LOSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LOSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 58,602"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58602

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 87,217"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87217

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 49,471"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49471

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 50,899"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50899

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 179,348"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,179348

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 100,303"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100303

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 156,647"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156647

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 75,779"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75779

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 107,056"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107056

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 99,257"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99257

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 66,157"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66157

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 90,028"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90028

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 144,742"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,144742

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 169,080"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169080
