[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LA PLATA - NR FARMINGTON (LPFN5L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LPFN5L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LPFN5L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 7,937"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7937

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 14,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14942

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 16,651"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16651

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 17,663"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17663

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 62,849"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62849

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 50,840"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50840

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 74,701"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74701

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 38,037"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38037

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 51,803"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51803

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 43,939"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43939

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 23,716"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23716

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 47,634"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47634

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 59,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59470

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 54,456"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54456
