[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LA PLATA - CO/NM STATE LINE (LPSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 37,704"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37704

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 70,397"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70397

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 50,790"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50790

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 44,959"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44959

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 154,598"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154598

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 87,576"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87576

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 137,044"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137044

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 74,606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74606

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 111,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,111123

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 87,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87559

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 46,168"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46168

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 78,972"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78972

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 142,382"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142382

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 132,692"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,132692
