[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LITTLE SNAKE - NR SAVERY (LSDW4L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LSDW4L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LSDW4L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 303,594"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,303594

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 456,342"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,456342

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 423,604"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,423604

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 458,182"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,458182

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 844,479"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,844479

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 841,273"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,841273

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 821,322"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,821322

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 1,120,950"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1120950

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 606,321"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,606321

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 658,884"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,658884

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 839,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,839507

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 649,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,649434

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,093,685"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1093685

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 743,167"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,743167
