[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LITTLE SNAKE - NR SLATER (LSRC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LSRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LSRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 230,780"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,230780

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 297,370"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,297370

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 278,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,278060

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 260,443"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260443

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 392,587"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,392587

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 376,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,376757

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 376,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,376837

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 553,789"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,553789

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 288,982"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,288982

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 285,021"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285021

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 513,438"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,513438

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 345,952"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,345952

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 528,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,528474

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 383,334"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,383334
