[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CONEJOS RIVER NEAR LASAUSES, CO. (LSZC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LSZC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LSZC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 24,734"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24734

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 16,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16621

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 12,531"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12531

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 24,968"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24968

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 39,449"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39449

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 32,743"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32743

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 40,702"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40702

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 21,309"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21309

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 24,608"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24608

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 26,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26575

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 35,661"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35661

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 33,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33090

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 43,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43575

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 40,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40465
