[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at La Junta, CO (LXHC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "LXHC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "LXHC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 19,527"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19527

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 85,642"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85642

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 81,753"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81753

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 285,197"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285197

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 158,993"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,158993

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 142,717"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142717

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 224,816"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,224816

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 110,671"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110671

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 188,102"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188102

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 118,947"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118947

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 129,593"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129593

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 165,677"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,165677

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 107,336"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107336

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 143,634"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143634
