[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "YAMPA - NR MAYBELL (MBLC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MBLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MBLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 258,312"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,258312

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 302,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,302368

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 431,722"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,431722

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 510,341"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,510341

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 706,255"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,706255

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 503,311"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,503311

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 537,322"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,537322

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 854,051"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,854051

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 518,319"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,518319

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 740,067"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,740067

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,113,449"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1113449

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 675,627"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,675627

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,147,027"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1147027

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 780,313"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,780313
