[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "MCELMO CREEK - NR CO-UT BORDER (MCEC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MCEC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MCEC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 33,283"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33283

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 44,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44087

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 48,112"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48112

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 33,088"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33088

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 129,719"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129719

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 86,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86297

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 145,837"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145837

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 83,278"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83278

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 101,194"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101194

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 73,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73804

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 34,172"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34172

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 65,035"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65035

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 121,384"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121384

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 93,385"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93385
