[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "MANCOS - MANCOS NR (MNRC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MNRC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MNRC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 75,829"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75829

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 119,990"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,119990

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 57,324"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57324

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 58,314"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58314

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 118,534"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118534

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 77,255"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77255

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 88,532"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88532

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 94,143"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94143

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 85,512"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85512

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 81,076"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81076

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 67,001"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67001

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 84,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84215

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 128,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128200

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 133,835"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133835
