[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "DOLORES - MCPHEE RESERVOIR (MPHC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MPHC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MPHC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 99,314"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99314

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 142,583"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142583

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 93,011"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93011

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 80,073"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80073

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 191,246"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191246

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 128,606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128606

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 162,241"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162241

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 119,303"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,119303

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 156,726"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156726

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 118,106"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118106

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 96,343"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96343

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 100,327"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100327

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 226,892"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,226892

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 162,312"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162312
