[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "GUNNISON - MORROW POINT RESERVOIR (MPSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MPSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MPSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 109,712"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109712

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 142,759"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142759

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 153,244"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153244

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 152,908"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,152908

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 232,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,232507

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 190,110"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190110

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 200,899"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,200899

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 265,945"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,265945

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 152,624"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,152624

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 177,622"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,177622

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 256,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,256072

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 209,857"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,209857

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 230,549"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,230549

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 221,608"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,221608
