[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "MANCOS - NR TOWAOC (MRTC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MRTC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MRTC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 36,967"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36967

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 67,986"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67986

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 61,038"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61038

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 43,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43565

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 168,871"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,168871

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 107,176"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107176

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 172,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,172215

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 93,524"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93524

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 128,680"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128680

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 98,567"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98567

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 46,667"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46667

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 88,068"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88068

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 162,606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162606

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 133,188"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133188
