[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE NEAR MONTE VISTA, CO (MVTC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "MVTC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "MVTC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 133,051"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133051

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 98,300"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98300

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 74,221"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74221

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 109,205"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109205

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 169,236"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169236

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 128,755"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,128755

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 154,927"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154927

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 109,356"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109356

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 120,078"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,120078

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 101,124"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101124

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 171,716"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171716

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 145,631"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145631

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 187,769"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,187769

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 150,571"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,150571
