[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "NAVAJO - NR CHROMO BLO OSO DIV DAM (NAVC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "NAVC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "NAVC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 103,377"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103377

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 140,637"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140637

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 75,193"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75193

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 106,011"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,106011

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 182,477"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182477

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 139,596"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139596

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 141,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141757

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 135,841"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,135841

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 121,045"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121045

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 104,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104607

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 95,669"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95669

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 96,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96621

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 143,158"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143158

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 174,574"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174574
