[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PURGATOIRE RVR (NMIC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "NMIC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "NMIC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 51,492"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51492

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 202,513"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,202513

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 105,808"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105808

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 511,437"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,511437

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 238,996"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,238996

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 228,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,228597

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 311,271"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,311271

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 155,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,155469

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 293,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,293072

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 161,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,161561

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 127,998"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127998

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 240,427"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,240427

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 222,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222575

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 195,865"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195865
