[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Nepesta, CO UP ELEV (NPTC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "NPTC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "NPTC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 28,640"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28640

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 38,563"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38563

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 39,306"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39306

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 147,296"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147296

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 71,166"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71166

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 68,534"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68534

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 110,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110797

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 44,469"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44469

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 72,545"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72545

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 69,689"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69689

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 56,730"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56730

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 58,222"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58222

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 132,564"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,132564

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 54,853"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54853
