[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Nepesta, CO (NPTC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "NPTC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "NPTC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16797

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 74,487"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74487

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 77,843"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77843

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 217,879"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,217879

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 135,886"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,135886

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 109,601"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,109601

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 211,378"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,211378

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 86,810"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86810

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 137,794"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137794

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 112,375"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112375

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 162,972"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162972

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 155,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,155434

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 168,357"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,168357

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 105,245"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105245
