[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LOS PINOS RIVER NEAR ORTIZ, CO. (ORTC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "ORTC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "ORTC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 188,836"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188836

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 232,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,232607

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 123,117"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,123117

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 176,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,176509

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 268,153"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,268153

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 222,378"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222378

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 221,454"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,221454

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 227,049"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227049

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 175,286"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,175286

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 158,008"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,158008

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 214,299"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214299

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 218,671"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,218671

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 300,461"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,300461

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 298,476"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,298476
