[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Pueblo Reservoir near Pueblo
UP ELEV (PBAC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PBAC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PBAC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 34,965"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34965

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 53,125"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53125

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 47,938"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47938

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 137,041"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137041

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 90,382"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90382

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 95,146"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95146

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 134,553"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134553

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 69,704"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69704

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 96,366"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96366

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 107,298"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107298

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 72,103"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72103

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 94,495"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,94495

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 143,332"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143332

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 69,584"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69584
