[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Pueblo Reservoir near Pueblo (PBAC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PBAC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PBAC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 13,296"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13296

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 45,069"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45069

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 53,686"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53686

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 123,901"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,123901

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 79,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79976

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 75,333"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75333

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 136,014"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,136014

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 65,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65072

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 104,769"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104769

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 90,390"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90390

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 99,612"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99612

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 125,441"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125441

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 100,815"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100815

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 70,424"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70424
