[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PLATEAU CREEK - NR CAMEO (PCCC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PCCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PCCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 297,963"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,297963

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 508,441"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,508441

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 302,593"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,302593

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 333,238"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,333238

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 488,248"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,488248

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 397,831"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,397831

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 425,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,425942

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 486,587"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,486587

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 339,640"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,339640

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 439,351"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,439351

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 553,816"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,553816

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 427,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,427090

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 557,753"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,557753

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 423,949"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,423949
