[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Pueblo Dam, CO (PDAC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PDAC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PDAC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 18"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 186"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,186

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 254"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,254

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 605"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,605

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 349"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,349

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 275"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 497"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,497

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,291

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 415"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,415

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 385"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,385

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 551"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,551

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 606"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,606

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 379"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,379

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 311"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,311
