[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Wellsville, CO (PDLC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PDLC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PDLC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 192,852"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192852

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 184,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,184465

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 125,462"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125462

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 410,896"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,410896

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 356,836"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,356836

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 268,573"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,268573

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 471,254"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,471254

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 190,647"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190647

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 301,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,301434

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 252,774"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,252774

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 382,380"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,382380

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 415,118"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,415118

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 423,718"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,423718

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 222,834"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222834
