[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Purgatoire River at Madrid, CO (PGMC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PGMC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PGMC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 42,314"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42314

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 79,037"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79037

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 39,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39474

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 95,678"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95678

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 66,973"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66973

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 58,457"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58457

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 99,784"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99784

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 60,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60090

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 68,592"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68592

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 59,650"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59650

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 36,823"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36823

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 60,864"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60864

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 80,005"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80005

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 61,713"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61713
