[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PURGATOIRE RVR UP ELEV (PGWC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PGWC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PGWC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 32,242"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32242

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 46,938"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46938

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 24,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24237

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 37,892"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37892

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 33,257"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33257

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 33,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33932

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 38,288"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38288

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 28,277"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28277

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 31,847"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31847

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 28,756"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28756

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 34,908"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34908

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 37,969"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37969

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 42,778"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42778

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 40,736"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40736
