[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PIEDRA - NR ARBOLES (PIDC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PIDC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PIDC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 459,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,459597

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 581,045"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,581045

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 238,548"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,238548

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 297,485"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,297485

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 606,853"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,606853

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 403,156"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,403156

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 497,115"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,497115

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 381,757"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,381757

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 408,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,408754

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 397,548"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,397548

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 365,319"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,365319

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 368,587"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,368587

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 583,515"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,583515

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 597,317"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,597317
