[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fountain Creek at Pinon, CO
UP ELEV (PNNC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PNNC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PNNC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 1,319"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1319

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 2,801"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2801

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 2,478"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2478

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 7,167"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7167

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 4,539"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4539

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 5,103"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5103

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 8,481"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8481

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 3,952"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3952

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 5,389"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5389

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 4,672"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4672

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 4,423"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4423

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 4,952"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4952

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 7,367"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,7367

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 4,117"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4117
