[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Fountain Creek at Pinon, CO (PNNC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PNNC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PNNC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 2,690"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2690

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 13,958"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13958

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 13,115"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13115

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 31,014"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31014

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 21,691"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21691

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 21,548"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21548

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 35,085"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35085

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 13,651"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13651

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 26,261"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26261

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 21,286"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21286

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 28,513"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28513

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 29,616"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29616

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 35,189"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35189

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 19,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19521
