[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "MUDDY CREEK - PAONIA RESERVOIR, NR BARDINE (PRSC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PRSC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PRSC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 163,599"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,163599

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 280,365"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,280365

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 180,027"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180027

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 178,000"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,178000

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 295,992"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,295992

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 232,054"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,232054

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 213,295"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,213295

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 266,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,266151

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 166,429"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166429

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 206,317"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,206317

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 257,512"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,257512

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 185,762"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,185762

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 261,675"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,261675

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 255,911"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255911
