[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Canon City, CO (PRTC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PRTC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PRTC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 69,507"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69507

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 92,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92509

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 84,077"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84077

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 204,563"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,204563

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 147,670"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147670

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 131,995"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131995

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 213,510"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,213510

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 90,124"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90124

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 154,646"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154646

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 133,854"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133854

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 139,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139942

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 168,368"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,168368

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 171,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,171033

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 95,571"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95571
