[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PINEY - NR STATE BRIDGE (PSBC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PSBC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PSBC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 63,865"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63865

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 56,432"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56432

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 61,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61386

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 82,663"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82663

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 99,762"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99762

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 79,913"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79913

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 65,106"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65106

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 116,719"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,116719

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 58,558"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58558

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 92,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92521

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 135,639"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,135639

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 121,736"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121736

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 118,308"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118308

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 105,975"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105975
