[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CONEJOS RIVER BELOW PLATORO RESERVOIR, CO (PTOC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "PTOC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "PTOC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 72,555"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72555

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 80,617"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80617

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 57,640"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57640

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 65,031"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65031

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 95,725"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95725

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 80,031"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80031

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 76,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76966

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 77,179"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77179

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 66,538"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66538

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 55,212"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55212

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 64,473"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64473

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 64,327"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64327

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 81,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81215

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 80,295"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80295
