[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO BLANCO - PAGOSA SPRINGS NR  BLANCO DAM BLO (RBPC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RBPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RBPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 86,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86999

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 102,833"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,102833

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 62,946"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62946

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 82,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82215

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 137,330"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137330

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 110,483"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110483

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 107,073"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107073

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 103,949"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103949

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 91,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91090

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 74,882"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74882

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 81,302"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81302

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 76,451"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76451

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 103,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103597

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 121,822"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,121822
