[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "UNCOMPAHGRE - RIDGWAY RESERVOIR (RBSC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RBSC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RBSC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 11,919"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11919

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 8,526"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,8526

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 11,131"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,11131

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 13,425"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13425

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 18,254"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18254

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 13,560"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13560

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 16,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16875

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 10,425"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,10425

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 12,198"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,12198

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 15,129"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15129

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 9,610"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,9610

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 15,226"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15226

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 20,203"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20203

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 16,744"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16744
