[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CRYSTAL - NR REDSTONE  AT AVALANCHE CREEK (RCYC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RCYC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RCYC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 172,747"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,172747

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 256,901"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,256901

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 205,287"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,205287

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 194,035"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,194035

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 299,612"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,299612

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 193,091"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,193091

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 181,263"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,181263

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 285,942"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285942

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 151,440"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,151440

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 201,772"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,201772

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 271,385"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,271385

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 203,351"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,203351

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 234,910"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,234910

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 250,291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,250291
