[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "EAGLE - REDCLIFF (RERC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RERC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RERC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 69,787"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69787

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 76,097"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76097

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 110,110"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110110

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 105,413"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105413

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 120,344"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,120344

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 97,095"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97095

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 79,239"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79239

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 140,555"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140555

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 77,416"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77416

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 86,310"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86310

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 122,785"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,122785

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 108,697"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108697

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 116,745"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,116745

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 96,723"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96723
