[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIFLE CREEK - NR RIFLE (RRGC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RRGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RRGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 37,291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37291

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 61,979"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61979

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 68,556"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68556

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 53,366"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53366

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 104,826"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104826

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 80,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80875

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 95,736"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95736

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 137,894"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137894

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 88,097"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88097

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 74,120"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,74120

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 96,632"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96632

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 66,967"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,66967

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 136,374"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,136374

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 88,250"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88250
