[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "RIO GRANDE AT WAGON WHEEL GAP, CO (RWGC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "RWGC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "RWGC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 657,703"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,657703

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 614,427"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,614427

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 394,612"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,394612

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 538,599"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,538599

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 644,607"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,644607

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 580,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,580060

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 591,493"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,591493

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 674,644"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,674644

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 571,562"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,571562

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 470,308"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,470308

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 726,877"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,726877

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 673,346"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,673346

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 729,161"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,729161

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 622,170"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,622170
