[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SANGRE DE CRISTO CREEK NEAR FORT GARLAND, CO. (SAFC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SAFC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SAFC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 100,697"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100697

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 131,496"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131496

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 47,424"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47424

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 130,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,130597

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 141,513"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141513

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 133,052"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133052

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 148,772"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,148772

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 75,779"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75779

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 97,947"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97947

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 86,230"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86230

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 95,062"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95062

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 97,540"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97540

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 130,459"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,130459

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 114,382"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,114382
