[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Salida, CO (SALC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SALC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SALC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 27,491"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27491

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 26,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26797

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 18,901"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18901

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 53,051"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53051

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 50,572"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50572

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 26,842"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26842

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 60,097"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60097

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 25,317"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25317

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 32,099"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32099

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 31,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31999

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 53,663"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53663

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 52,906"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52906

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 48,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48521

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 36,943"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36943
