[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAN ANTONIO RIVER AT ORTIZ, CO. (SAOC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SAOC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SAOC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 96,890"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96890

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 87,038"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87038

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 56,525"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56525

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 90,800"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90800

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 141,612"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141612

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 138,403"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,138403

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 141,661"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,141661

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 101,154"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101154

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 93,726"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,93726

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 86,938"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86938

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 102,321"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,102321

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 108,250"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108250

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 151,121"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,151121

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 150,664"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,150664
