[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SURFACE CK - AT CEDAREDGE (SCCC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SCCC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SCCC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 61,190"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61190

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 104,047"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,104047

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 45,181"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45181

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 49,386"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49386

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 73,001"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73001

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 53,276"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53276

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 58,190"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58190

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 78,006"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,78006

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 47,354"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47354

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 49,367"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49367

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 51,149"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51149

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 38,878"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,38878

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 69,358"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,69358

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 58,225"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58225
