[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "YAMPA - BLO STAGECOACH RESERVOIR (SCHC2R_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SCHC2R_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SCHC2R_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 15,722"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15722

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 13,017"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,13017

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 16,257"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16257

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 17,262"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,17262

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 21,608"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21608

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 18,063"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,18063

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 16,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16297

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 27,905"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27905

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 15,134"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15134

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 19,599"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19599

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 29,472"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29472

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 22,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22935

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 30,487"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30487

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 23,763"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,23763
