[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Shadow Mountain Upper (SDMCOUP) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SDMCOUP.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SDMCOUP-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 71,035"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71035

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 73,126"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73126

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 70,562"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70562

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 79,063"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,79063

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 83,491"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83491

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 76,581"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76581

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 76,113"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76113

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 134,103"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,134103

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 70,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,70178

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 82,231"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,82231

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 100,037"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100037

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 98,429"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98429

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 102,656"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,102656

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 86,698"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86698
