[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Shadow Mountain Lower (SDMCOLO) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SDMCOLO.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SDMCOLO-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 34,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34090

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 44,290"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44290

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 40,097"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40097

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 54,635"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54635

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 55,875"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55875

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 59,057"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59057

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 54,731"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54731

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 95,325"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95325

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 50,641"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,50641

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 60,581"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60581

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 76,855"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,76855

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 65,590"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65590

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 86,213"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86213

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 85,197"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85197
