[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CIMARRON - SILVER JACK RES, NR CIMARRON (SJAC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SJAC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SJAC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 39,388"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39388

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 63,911"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63911

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 57,739"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57739

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 58,983"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58983

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 85,079"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,85079

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 68,373"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68373

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 71,234"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71234

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 101,520"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101520

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 57,269"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57269

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 67,911"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,67911

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 98,617"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98617

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 98,026"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,98026

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 87,222"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87222

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 77,269"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77269
