[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAN JUAN - NR CARRACAS (SJCC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SJCC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SJCC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 224,433"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,224433

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 273,072"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,273072

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 150,996"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,150996

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 190,962"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,190962

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 510,138"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,510138

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 343,705"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,343705

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 452,774"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,452774

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 234,268"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,234268

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 340,710"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,340710

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 289,765"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,289765

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 212,318"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,212318

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 270,576"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,270576

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 350,434"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,350434

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 477,906"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,477906
