[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SLATER FORK - NR SLATER (SLFC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SLFC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SLFC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 57,337"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57337

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 102,155"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,102155

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 88,964"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,88964

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 97,230"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,97230

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 165,742"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,165742

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 153,209"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153209

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 174,905"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,174905

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 244,971"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,244971

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 130,848"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,130848

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 139,792"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139792

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 214,764"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214764

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 177,754"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,177754

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 255,838"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255838

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 183,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,183676
