[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "CULEBRA CREEK AT SAN LUIS, CO (SLUC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SLUC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SLUC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 150,947"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,150947

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 193,318"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,193318

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 90,742"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90742

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 162,473"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162473

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 167,131"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,167131

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 182,014"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182014

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 203,615"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,203615

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 118,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118543

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 143,567"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143567

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 131,128"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,131128

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 160,243"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160243

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 166,737"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166737

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 195,408"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,195408

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 209,613"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,209613
