[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAN MIGUEL - NR PLACERVILLE (SMPC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SMPC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SMPC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 228,075"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,228075

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 274,958"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274958

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 255,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255297

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 274,853"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274853

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 376,006"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,376006

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 335,886"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,335886

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 331,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331676

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 442,647"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,442647

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 319,260"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,319260

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 309,670"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,309670

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 405,264"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,405264

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 389,311"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,389311

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 476,215"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,476215

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 387,995"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,387995
