[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAN MIGUEL - AT URAVAN (SMUC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SMUC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SMUC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 202,322"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,202322

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 186,037"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,186037

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 164,167"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164167

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 157,462"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,157462

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 283,880"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,283880

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 233,951"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,233951

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 273,992"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,273992

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 241,583"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,241583

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 246,961"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,246961

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 245,262"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,245262

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 214,569"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,214569

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 211,243"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,211243

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 401,725"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,401725

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 231,236"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,231236
