[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SAN MIGUEL - BROOKS BRIDGE NR NUCLA (SNMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SNMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SNMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 233,977"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,233977

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 180,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180797

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 188,002"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188002

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 203,418"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,203418

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 335,014"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,335014

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 266,087"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,266087

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 287,571"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,287571

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 294,936"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,294936

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 274,272"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,274272

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 269,492"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,269492

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 307,962"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,307962

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 250,811"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,250811

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 460,433"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,460433

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 331,506"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,331506
