[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "NF GUNNISON - NR SOMERSET (SOMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 208,667"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,208667

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 305,769"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,305769

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 266,829"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,266829

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 247,188"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,247188

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 380,563"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,380563

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 287,947"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,287947

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 277,588"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,277588

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 367,297"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,367297

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 204,325"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,204325

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 253,200"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,253200

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 348,015"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,348015

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 276,168"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,276168

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 283,376"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,283376

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 361,888"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,361888
