[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "SOUTH FORK RIO GRANDE AT SOUTH FORK, CO (SRGC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "SRGC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "SRGC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 314,055"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,314055

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 348,048"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,348048

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 201,528"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,201528

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 246,104"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,246104

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 362,091"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,362091

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 266,832"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,266832

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 267,005"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,267005

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 264,090"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,264090

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 235,672"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,235672

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 193,811"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,193811

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 328,265"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,328265

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 279,585"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,279585

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 364,170"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,364170

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 317,821"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,317821
