[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "YAMPA - AT STEAMBOAT SPRINGS (STMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "STMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "STMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 225,928"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,225928

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 237,009"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,237009

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 289,926"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,289926

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 275,151"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,275151

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 315,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,315668

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 277,465"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,277465

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 260,983"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260983

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 454,440"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,454440

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 210,800"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,210800

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 248,040"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,248040

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 444,960"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,444960

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 329,247"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,329247

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 423,760"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,423760

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 305,851"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,305851
