[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TRINCHERA CREEK BELOW SMITH RES, NR BLANCA, CO (TBSC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TBSC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TBSC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 47,863"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47863

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 57,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,57804

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 21,989"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21989

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 54,644"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54644

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 45,708"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45708

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 55,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55668

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 68,097"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68097

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 34,017"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34017

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 39,401"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,39401

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 35,452"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35452

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 35,926"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35926

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 37,339"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37339

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 45,551"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45551

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 43,613"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43613
