[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TWO BUTTE CRK (TBTC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TBTC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TBTC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 22,718"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22718

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 86,648"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86648

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 45,755"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45755

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 305,676"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,305676

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 83,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,83565

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 77,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77060

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 140,802"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,140802

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 59,534"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59534

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 124,762"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,124762

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 77,407"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77407

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 60,137"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60137

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 129,881"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129881

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 118,940"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,118940

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 77,291"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77291
