[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TRINIDAD LAKE (TDDC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TDDC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TDDC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 29,141"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,29141

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 58,562"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58562

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 30,023"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30023

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 87,142"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87142

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 55,617"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,55617

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 47,672"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47672

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 87,588"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87588

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 49,630"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49630

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 60,936"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60936

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 49,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,49098

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 27,582"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27582

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 47,847"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,47847

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 65,864"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65864

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 54,132"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54132
