[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "ALAMOSA RIVER ABOVE TERRACE RESERVOIR, CO. (TERC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TERC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TERC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 164,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164123

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 145,921"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145921

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 113,293"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113293

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 125,193"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125193

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 182,803"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182803

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 162,144"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162144

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 156,365"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156365

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 145,098"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,145098

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 133,861"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133861

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 105,859"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105859

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 146,089"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146089

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 133,551"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,133551

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 182,794"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,182794

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 156,451"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156451
