[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PURGATOIRE RVR (THTC2L) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "THTC2L.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "THTC2L-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 53,204"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53204

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 233,305"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,233305

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 119,924"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,119924

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 536,132"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,536132

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 260,309"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260309

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 219,619"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,219619

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 330,753"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,330753

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 156,391"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,156391

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 304,821"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,304821

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 143,101"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143101

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 139,578"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,139578

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 236,824"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,236824

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 269,166"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,269166

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 220,050"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,220050
