[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PURGATOIRE RVR UP ELEV (THTC2U) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "THTC2U.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "THTC2U-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 36,186"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36186

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 105,051"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,105051

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 53,411"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,53411

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 165,322"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,165322

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 113,042"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,113042

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 96,737"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96737

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 160,715"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160715

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 73,133"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73133

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 120,860"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,120860

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 73,060"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73060

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 51,908"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,51908

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 91,702"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91702

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 127,431"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,127431

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 103,859"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103859
