[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TWIN LAKES INFLOW (TINC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TINC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TINC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 43,818"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43818

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 58,141"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58141

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 72,531"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,72531

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 84,712"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84712

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 96,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,96223

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 80,767"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80767

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 86,035"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86035

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 125,219"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,125219

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 73,554"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,73554

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 90,064"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90064

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 107,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,107033

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 110,792"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,110792

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 111,242"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,111242

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 89,906"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,89906
