[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LAKE CREEK (TLRC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TLRC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TLRC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 16,064"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16064

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 16,317"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,16317

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 20,373"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20373

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 30,629"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30629

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 28,602"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28602

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 22,400"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22400

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 26,139"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26139

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 34,104"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34104

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 22,495"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22495

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 26,505"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26505

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 42,245"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42245

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 41,002"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41002

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 34,163"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34163

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 28,334"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28334
