[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TOMICHI CREEK - GUNNISON (TOMC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TOMC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TOMC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 365,177"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,365177

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 351,470"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,351470

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 302,511"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,302511

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 405,256"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,405256

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 504,468"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,504468

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 403,988"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,403988

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 457,812"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,457812

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 447,306"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,447306

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 309,408"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,309408

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 364,915"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,364915

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 578,552"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,578552

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 524,499"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,524499

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 535,575"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,535575

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 596,132"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,596132
