[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TAYLOR - TAYLOR PARK RESERVOIR (TPIC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TPIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TPIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 92,546"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,92546

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 91,559"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,91559

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 86,565"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86565

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 142,342"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142342

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 147,591"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,147591

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 117,445"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,117445

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 124,079"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,124079

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 142,037"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,142037

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 100,160"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,100160

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 119,239"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,119239

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 162,626"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162626

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 162,367"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162367

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 164,026"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164026

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 158,294"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,158294
