[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "LAKE FORK CRK (TQLC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TQLC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TQLC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 21,572"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,21572

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 24,770"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,24770

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 36,433"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,36433

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 40,276"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40276

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 46,905"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46905

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 37,752"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37752

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 32,836"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32836

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 56,541"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56541

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 31,079"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31079

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 33,146"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33146

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 46,520"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,46520

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 44,091"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44091

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 42,986"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42986

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 40,201"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40201
