[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "TRINCHERA C AB TURNERS RANCH, NR FT GARLAND, CO (TTRC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "TTRC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "TTRC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 44,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,44223

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 65,346"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65346

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 27,363"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27363

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 61,543"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,61543

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 48,362"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48362

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 52,062"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,52062

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 58,192"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58192

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 42,017"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42017

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 48,993"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,48993

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 37,355"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37355

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 56,941"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56941

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 58,610"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,58610

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 68,580"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68580

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 68,122"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,68122
