[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "UTE CREEK NEAR FORT GARLAND, CO (UFGC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "UFGC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "UFGC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 32,224"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32224

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 37,399"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37399

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 14,785"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,14785

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 37,327"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37327

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 41,582"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41582

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 37,792"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37792

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 41,384"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41384

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 28,149"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28149

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 31,064"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,31064

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 25,391"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,25391

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 30,416"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30416

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 27,008"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27008

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 41,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,41178

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 33,112"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33112
