[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "PLATEAU CK - VEGA RES NR COLLBRAN (VEGC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "VEGC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "VEGC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 15,284"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,15284

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 32,915"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,32915

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 19,013"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,19013

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 20,347"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,20347

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 34,728"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34728

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 27,799"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27799

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 27,450"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,27450

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 35,504"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,35504

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 22,331"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,22331

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 30,132"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,30132

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 37,431"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,37431

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 26,466"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,26466

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 33,288"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33288

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 28,381"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,28381
