[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WHITE - NR WATSON (WATU1L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WATU1L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WATU1L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 84,591"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,84591

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 187,187"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,187187

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 103,591"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103591

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 164,422"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,164422

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 472,033"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,472033

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 149,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,149237

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 282,911"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,282911

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 316,270"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,316270

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 225,116"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,225116

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 527,024"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,527024

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 470,978"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,470978

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 285,333"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,285333

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 479,838"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,479838

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 333,024"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,333024
