[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WILLOW CK RESERVOIR (WCDC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WCDC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WCDC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 2,133"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2133

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 2,927"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2927

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 2,652"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,2652

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 3,581"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3581

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 4,304"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4304

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 4,204"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4204

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 3,597"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3597

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 5,585"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,5585

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 3,653"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3653

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 3,961"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3961

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 4,917"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4917

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 3,521"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,3521

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 4,788"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4788

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 4,797"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,4797
