[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WEST DIVIDE CREEK - NR RAVEN (WETC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WETC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WETC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 33,698"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,33698

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 56,929"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,56929

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 40,973"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,40973

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 45,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,45065

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 75,178"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75178

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 63,943"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,63943

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 59,093"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,59093

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 71,675"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,71675

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 43,375"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43375

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 54,578"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,54578

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 86,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,86804

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 64,668"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64668

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 77,061"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,77061

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 62,983"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,62983
