[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WHITE - NR RANGELY BLO BOISE CREEK (WHBC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WHBC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WHBC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 129,025"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,129025

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 229,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,229561

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 227,495"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,227495

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 310,344"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,310344

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 593,727"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,593727

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 260,781"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,260781

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 448,466"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,448466

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 509,976"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,509976

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 415,426"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,415426

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 597,966"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,597966

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 763,561"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,763561

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 383,066"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,383066

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 800,153"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,800153

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 504,546"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,504546
