[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WHITE - BLO MEEKER (WHIC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WHIC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WHIC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 42,804"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,42804

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 64,506"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,64506

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 80,367"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,80367

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 81,720"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,81720

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 153,924"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,153924

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 75,672"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,75672

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 108,206"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,108206

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 146,608"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,146608

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 103,864"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,103864

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 144,123"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,144123

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 180,824"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180824

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 95,745"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95745

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 188,191"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188191

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 112,933"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,112933
