[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WOLFORD MOUNTAIN RESERVOIR (WORC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WORC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WORC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 187,762"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,187762

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 215,982"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,215982

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 229,404"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,229404

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 222,140"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222140

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 271,671"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,271671

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 222,894"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,222894

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 191,862"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191862

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 347,301"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,347301

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 166,500"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,166500

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 231,663"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,231663

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 346,688"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,346688

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 263,661"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,263661

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 362,490"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,362490

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 290,664"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,290664
