[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "WHITE - NR MEEKER (WRMC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WRMC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WRMC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 525,732"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,525732

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 692,393"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,692393

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 799,948"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,799948

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 692,910"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,692910

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 914,315"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,914315

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 787,286"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,787286

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 822,223"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,822223

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 1,321,004"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1321004

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 672,926"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,672926

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 754,762"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,754762

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 1,193,107"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1193107

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 870,031"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,870031

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 1,224,281"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,1224281

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 838,920"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,838920
