[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "Arkansas River at Wellsville, CO (WSVC2) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "WSVC2.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "WSVC2-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 138,288"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,138288

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 151,667"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,151667

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 99,209"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,99209

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 196,065"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,196065

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 188,756"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,188756

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 154,848"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,154848

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 198,930"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,198930

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 162,155"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,162155

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 137,362"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,137362

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 143,023"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,143023

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 230,932"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,230932

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 198,618"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,198618

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 234,160"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,234160

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 183,339"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,183339
