[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "YAMPA - ABV STAGECOACH RESERVOIR (YASC2H_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "YASC2H_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "YASC2H_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 180,939"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,180939

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 160,474"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,160474

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 199,396"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,199396

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 216,621"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,216621

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 255,567"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,255567

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 253,751"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,253751

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 243,708"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,243708

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 392,906"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,392906

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 192,107"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,192107

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 230,936"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,230936

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 360,987"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,360987

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 290,307"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,290307

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 399,709"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,399709

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 276,237"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,276237
