[Product]

ProductType = "Graph"
TotalWidth = "850"
TotalHeight = "600"
MainTitleString = "YAMPA - AT DEERLODGE PARK (YDLC2L_F) SNODAS SWE Volume Gain, Cumulative"
MainTitleFontSize = 16
MainTitleFontStyle = Bold
SubTitleString = "(Each line corresponds to a Water Year starting Oct 1)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitleFontStyle = "Bold"
LeftYAxisTitleFontSize = "16"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Snow Water Equivalent (SWE) Volume Gain, Cumulative (acft)"
LeftYAxisLabelPrecision = "0"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

LeftYAxisLegendPosition = "Left"
LegendFormat = "SNODAS WY %z"

# Properties for each trace, one for each water year
# Colors are random except that the last year is highlighted with line width of 3

[Data 1.1]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2004]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2004"

[Data 1.2]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2005]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2005"

[Data 1.3]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2006]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2006"

[Data 1.4]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2007]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2007"

[Data 1.5]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2008]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2008"

[Data 1.6]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2009]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2009"

[Data 1.7]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2010]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2010"

[Data 1.8]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2011]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2011"

[Data 1.9]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2012]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2012"

[Data 1.10]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2013]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2013"

[Data 1.11]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2014]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2014"

[Data 1.12]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2015]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2015"

[Data 1.13]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2016]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2016"

[Data 1.14]

TSID = "YDLC2L_F.SNODAS.SWE-Volume-Cumulative.Day[2017]"
TSAlias = "YDLC2L_F-SNODAS-SWE-Volume-Cumulative-Day-2017"

Color = "Blue"
LineWidth = 3


[Annotation 1.1]

AnnotationID = "YearLabel1"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2004: 34,858"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,34858

[Annotation 1.2]

AnnotationID = "YearLabel2"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2005: 65,741"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,65741

[Annotation 1.3]

AnnotationID = "YearLabel3"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2006: 43,623"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,43623

[Annotation 1.4]

AnnotationID = "YearLabel4"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2007: 87,006"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,87006

[Annotation 1.5]

AnnotationID = "YearLabel5"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2008: 169,280"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,169280

[Annotation 1.6]

AnnotationID = "YearLabel6"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2009: 60,213"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,60213

[Annotation 1.7]

AnnotationID = "YearLabel7"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2010: 95,446"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,95446

[Annotation 1.8]

AnnotationID = "YearLabel8"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2011: 155,935"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,155935

[Annotation 1.9]

AnnotationID = "YearLabel9"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2012: 90,509"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,90509

[Annotation 1.10]

AnnotationID = "YearLabel10"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2013: 183,283"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,183283

[Annotation 1.11]

AnnotationID = "YearLabel11"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2014: 229,792"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,229792

[Annotation 1.12]

AnnotationID = "YearLabel12"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2015: 101,999"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,101999

[Annotation 1.13]

AnnotationID = "YearLabel13"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2016: 250,987"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,250987

[Annotation 1.14]

AnnotationID = "YearLabel14"
Color = black
Order = OnTopOfData
ShapeType = Text
XAxisSystem = Percent
YAxisSystem = Data
Text = "2017: 191,158"
TextPosition = Left
FontSize = 12
FontStyle = Bold
Point = 100,191158
