# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: SNODAS Tools (User Manual)
pages:
- 'Home': index.md
- 'SNODAS Tools Data ':
  - 'Overview': data/overview.md
  - 'Input Data': data/data.md
- 'SNODAS Tools Process':
  - 'Overview': process/overview.md
  - 'Processing Steps': process/processing-steps.md
  - 'Additional Details' : process/additional-details.md
- 'SNODAS Tools Products':
  - 'Overview': products/overview.md
  - 'CDSS SNODAS Tools Web Application': products/webApp.md
  - 'Products and Downloads': products/products.md
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Do not include the repo because it shows an irritating edit icon on every page
#repo_url: https://github.com/OpenWaterFoundation/cdss-app-snodas-tools
site_description: SNODAS Tools (User Manual) 
site_author: Open Water Foundation
site_favicon: snodas-tools-favicon.png
#copyright: TBD
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
