# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: SNODAS Tools (Developer Manual)
pages:
- 'Home': index.md
- 'Development Environment':
    - 'Overview': 'dev-env/overview.md'
    - 'Machine':  'dev-env/machine.md'
    - 'QGIS and Bundled Python': 'dev-env/qgis.md'
    - 'TSTool': 'dev-env/tstool.md'
    - 'Git': 'dev-env/git.md'
    - 'Python (for MkDocs)': 'dev-env/python.md'
    - 'pip': 'dev-env/pip.md'
    - 'MkDocs': 'dev-env/mkdocs.md'
    - 'pytest': 'dev-env/pytest.md'
    - 'PyCharm': 'dev-env/pycharm.md'
- 'Initial Project Setup':
    - 'Overview': project-init/overview.md
    - 'Create Development Folder': 'project-init/dev-folder.md'
# the following may be useful to make sure PyCharm starts with proper Python
#    - 'Create Script to run PyCharm': 'project-init/pycharm-script.md'
    - 'GitHub Git Repository': 'project-init/github.md'
    - 'Developer Documentation (MkDocs)': 'project-init/dev-doc.md'
    - 'User Documentation (MkDocs)': 'project-init/user-doc.md'
    - 'PyCharm Project': 'project-init/pycharm-project.md'
    - 'pytest': 'project-init/pytest.md'
- 'New Developer Setup':
    - 'Overview': 'dev-new/overview.md'
- 'Deployed Environment':
    - 'Overview': 'deployed-env/overview.md'
    - 'Troubleshooting': 'deployed-env/troubleshooting.md'
- 'Software Design':
    - 'Overview': 'software-design/overview.md'
- 'Development Tasks':
    - 'Overview': 'dev-tasks/overview.md'
    - 'Previous Tool Version': 'dev-tasks/previous-tool.md'
    - 'Software Design': 'dev-tasks/software-design.md'
    - 'PyCharm Troubleshooting': 'dev-tasks/pycharm-trouble.md'
    - 'Git Workflow': 'dev-tasks/git.md'
    - 'Documenting': 'dev-tasks/doc.md'
    - 'Building and Running': 'dev-tasks/build-run.md'
    - 'Testing': 'dev-tasks/test.md'
    - 'Deploying': 'dev-tasks/deploy.md'
    - 'Future Enhancements': 'dev-tasks/future-enhancements.md'
theme: readthedocs
repo_url: https://github.com/OpenWaterFoundation/cdss-app-snodas-tools
site_description: SNODAS Tools (Developer Manual) 
site_author: Open Water Foundation
site_favicon: snodas-tools-favicon.png
#copyright: TBD
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
